# Generated by Django 5.1.6 on 2025-03-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0002_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
