services:
  - type: web
    name: eduflow-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python eduflow/manage.py collectstatic --noinput
      python eduflow/manage.py migrate
    startCommand: gunicorn eduflow.eduflow.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: eduflow.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
