services:
  - type: web
    name: eduflow-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python eduflow/manage.py collectstatic --noinput
    startCommand: gunicorn eduflow.eduflow.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: eduflow.eduflow.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: "1"
