# Generated by Django 5.1.6 on 2025-03-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='mark',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
