# Generated by Django 5.1.6 on 2025-03-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_leaderboard_mark_alter_leaderboard_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='rank',
        ),
    ]
