# Generated by Django 5.1.6 on 2025-03-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_leaderboard_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='is_mark_updated',
            field=models.BooleanField(default=False),
        ),
    ]
