# Generated by Django 5.1.6 on 2025-03-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_leaderboard_is_mark_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='is_mark_updated',
        ),
    ]
