# Generated by Django 5.1.6 on 2025-02-25 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_file', models.FileField(blank=True, null=True, upload_to='assignment/')),
                ('description', models.TextField(null=True)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('submission_deadline', models.DateTimeField()),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
            ],
        ),
    ]
