# Generated by Django 5.1.6 on 2025-03-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_assignmentsubmission'),
        ('teacher', '0002_assignmenttask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmenttask',
            name='students',
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='students',
            field=models.ManyToManyField(to='student.studentprofile'),
        ),
    ]
