# Generated by Django 5.1.6 on 2025-03-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_assignmenttask_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenttask',
            name='submission_deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
