# Generated by Django 5.1.6 on 2025-03-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_leaderboard_is_mark_updated'),
        ('teacher', '0005_assignmenttask_blocked_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenttask',
            name='blocked_students',
            field=models.ManyToManyField(null=True, related_name='blocked_tasks', to='student.studentprofile'),
        ),
    ]
