# Generated by Django 5.2.1 on 2025-05-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_assignmenttask_blocked_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
